import Head from 'next/head'
import Image from 'next/image'
import { AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube } from 'react-icons/ai';
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import Rashid from "../public/boy2.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import { Inter } from '@next/font/google'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <>
    <div  className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-stone-600 md:px-20 lg:px-40">
      <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Personal Portfolio</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-indigo-400 text- to-violet-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://drive.google.com/file/d/1Z5m_8t908USiHRJP4ynYjwbOPH9b6Jwn/view?usp=share_link"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-3xl py-2 text-indigo-400 font-medium dark:text-teal-400 md:text-6xl">
              Mohammad Rashid Javed
            </h2>
            <h3 className="text-1.5xl py-2 text-rose-400 dark:text-emerald-500 md:text-3xl">
              Developer and designer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Providing services for programming and design content
              needs. Join me down below and let's get cracking!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <AiFillTwitterCircle />
              <AiFillLinkedin />
              <AiFillYoutube />
            </div>
            <div className="mx-auto bg-gradient-to-b from-cyan-600 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image alt='' src={Rashid} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-orange-700 ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a web designer and
              developer, I've done many programming languages courses from online platfroms
              
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-yellow-800 flex-1">
              <Image alt='' src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white ">
                Beautiful Designs
              </h3>
              <p className="py-2 dark:text-lime-100">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600 dark:text-emerald-200">Design Tools I Use</h4>
              <p className="text-gray-800 py-1 dark:text-white">Photoshop</p>
              <p className="text-gray-800 py-1 dark:text-white">Illustrator</p>
              <p className="text-gray-800 py-1 dark:text-white">Figma</p>
              <p className="text-gray-800 py-1 dark:text-white">Indesign</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-yellow-800 flex-1">
              <Image alt='' src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-2 pb-10 dark:text-lime-100 ">
               Qualification
              </h3>
              <h3 className="text-lg font-medium pt-5 pb-1  dark:text-lime-100">
                Diploma <br/>
                2016 to 2019
              </h3>
              <p className="py-2 dark:text-white">
                I have complited 3 years diploma course in <span className="text-teal-500">ITESM ( Information Technology Enable to Service Management) </span> from <span className="text-teal-500">Rajokri Institute of Technology (RIT Delhi) </span>
              </p>
              <h3 className="text-lg font-medium pt-3 pb-1 dark:text-lime-100">
                BCA (Bachlor in Computer Application)
                <br/>
                2021 to 2023
              </h3>
              <p className="py-2 dark:text-white">
                Now I am pursuing 3 years <span className="text-teal-500">BCA ( Bachlor in Computer Application ) </span> course from <span className="text-teal-500"> Indira Gandhi National Open University (IGNOU) </span>
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-yellow-800 flex-1">
              <Image alt='' src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-lime-100">Consulting</h3>
              <p className="py-2 dark:text-white">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className="py-4 text-teal-600"> Languages & Design Tools I Use</h4>
              <p className="text-gray-800 py-1 dark:text-white">C <br/> C++ <br/> JAVA <br/> Python <br/> Python With machine learning <br/> Java Scripet  <br/> NodeJS <br/>NextJS <br/> </p>
              <p className="text-gray-800 py-1 dark:text-white">VS Code</p>
              {/* <p className="text-gray-800 py-1"></p>
              <p className="text-gray-800 py-1"></p> */}
            </div>
          </div>
        </section>
      </main>
      </div>
    </>
  )
}
